#!/bin/sh

. /usr/lib/tlvince/lib-bash/getConfig.sh
. $(getConfig ytmp)

[ $INTERFACE ] || {
    echo "$0: error: INTERFACE not set in /etc/ytmp.conf" >&2
    exit 1
}

rm /tmp/ytmpurls 2> /dev/null

FILTERS="
    s/GET \/ HTTP\/1\.1\.//                                                 # Unwanted GET headers
    s/.*\/\([0-9]*\) .*/host=vimeo\nid=\1/g                                 # Vimeo video ID
    s/.*=\([_a-zA-Z0-9-]\{11,11\}\)[ &].*/host=youtube\nid=\1/              # Youtube video ID
    s/.*video_id%22%3A%22\([_a-zA-Z0-9-]\{11,11\}\).*/host=youtube\nid=\1/  # Youtube channel video ID
"

ngrep -W byline -qil 'get|session' tcp dst port 80 -d "$INTERFACE" | \
egrep --line-buffered -i "(get\ /watch|GET \/[0-9]* .*|^session_token.*)" | \
sed --unbuffered -e "$FILTERS" >> /tmp/ytmpurls &

exit 0
