#!/bin/bash

CONFIG="${XDG_CONFIG_HOME:-"$HOME/.config"}/ytmp/"
if [[ -f "$CONFIG/ytmp.conf" ]]; then
    . "$CONFIG/ytmp.conf"
else
    . /etc/ytmp.conf
fi

ytplay() {
  echo "[ytmpc] Now playing: $title"
  mplayer -cache 2048 "$vidurl" > /dev/null 2>&1
}

ytdownload() {
  echo "[ytmpc] Now downloading: $title"
  youtube-dl --max-quality="$MAXQUAL" -o "${DWN:-$HOME}/%(stitle)s.%(ext)s" "$url"
}

ytdlandplay() {
  local log="/tmp/youtube-dl.log"
  ytdownload | tee "$log"
  vidurl="$(grep -F Destination "$log" | awk '{print $3}')"
  ytplay &
}

_dmenu() {
  choice=$(echo -e "View in mplayer\nDownload" | dmenu -i)

  case "$choice" in
    "View in mplayer") ytplay &;;
    "Download") ytdownload &;;
    "View in mplayer|Download") ytdlandplay &;;
  esac
}

_zenity() {
  choice=$(zenity --list --checklist --text="$title" --hide-header --column "1" \
             --column "2" TRUE "View in mplayer" FALSE "Download")

  case "$choice" in
    "View in mplayer") ytplay &;;
    "Download") ytdownload &;;
    "View in mplayer|Download") ytdlandplay &;;
  esac
}

_kdialog() {
  choice="$(kdialog --checklist "$title" 1 "View with mplayer (default)" on \
              2 "Download" off)"

  case "$choice" in
    "1") ytplay &;;
    "2") ytdownload &;;
    "1|2") ytdlandplay &;;
  esac
}
lasturl=""
while(true); do
  if [[ -f /tmp/ytmdurls ]]; then
    url="$(tail -n 1 /tmp/ytmdurls)"
    if [[ "$url" != "$lasturl" ]]; then
      title="$(youtube-dl -e "$url")"
      vidurl="$(youtube-dl --max-quality="$MAXQUAL" -g "$url")"
      case "$GUI" in
        "none") ytplay &;;
        "zenity") _zenity;;
        "kdialog") _kdialog;;
        "dmenu") _dmenu;;
      esac
    fi
    lasturl="$url"
  fi
  sleep 1
done

