#!/bin/sh

source /etc/ytmp.conf

rm /tmp/ytmdurls 2> /dev/null
ngrep -W byline -qilw 'get' tcp dst port 80 -d $INTERFACE | grep  --line-buffered -i "get\ /watch" | sed --unbuffered 's/.*=\([_a-zA-Z0-9-]\{11,11\}\)[ &].*/\1/' >> /tmp/ytmdurls
