#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/ytmpd`
case "$1" in
  start)
    stat_busy "Starting ytmpd"
    [ -z "$PID" ] && /usr/bin/ytmpd
    if [ $? -eq 0 ]; then
	add_daemon ytmpd
	stat_done
    else
	stat_fail
    fi
    ;;
  stop)
    stat_busy "Stopping ytmpd"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -ne 0 ]; then
      stat_fail
    else
      rm_daemon ytmpd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
